<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>1902__BAPE</title>
		<style>
		@import url('https://fonts.googleapis.com/css?family=Nunito:300,400,600');
		</style>
		<link rel="stylesheet" type="text/css" href="css/style.css" />
	</head>
	<body>
		<main>
			<div class = "bape">
				<svg class="scene" width="100%" height="100vh" preserveAspectRatio="none" viewBox="0 0 1920 1080" xmlns:pathdata="http://www.codrops.com/">
					<?php echo file_get_contents("assets/svg/bapes-one.svg"); ?>
			</div>
			<div class="content">
				<div class = "wrap">
					<h1 class="title">Botanic Wisdom</h2>
					<h5>
						It’s a myth that our reactions to danger are fight or flight. There’s a third option often pursued: to gather for reassurance, protection, strength, and insight.
						<br><br>
						As election results poured in Tuesday night, I saw people reaching out tssso ask for support and solidarity or to offer it. I saw those of us who will probably not be targeted pledge to stand with those who are already being assaulted and insulted and menaced and beaten. I saw people preparing for something that as a kid who grew up fearfully devouring Jewish holocaust literature I’ve been anxiously imagining all my life: what it might look like to provide a secret annex—and beyond that one history of oppression, what it might look like to be part of an underground railroad, a White Rose resistance movement, an anti-Apartheid movement.
						<br><br>
						I’ve written about hope, and this is a tough time to hope. I’ve also written about survival, and we survive by coming together. This election was a referendum on coming together and coming apart, but I know that most of us in the face of earthquakes, hurricanes, bombing raids do come together, and I thought it might be useful to offer up a little of that from my book on the subject, A Paradise Built in Hell.
						<br><br>
						This past week, we’ve been given hell; survival for some of us is going to depend on how well we build the paradises of active love, sanctuary, refuge, and generosity. Love and empathy are acts of imagination, imagination is an act of courage, of risk; heroic love is what is going to get us through as much as we can. Here’s a little bit about what that has looked like before.
						<br><br>
						Who are you? Who are we? In times of crisis, these are life and death questions. Thousands of people survived Hurricane Katrina because grandsons or aunts or neighbors or complete strangers reached out to those in need all through the Gulf Coast and because an armada of boat owners from the surrounding communities and as far away as Texas went into New Orleans to pull stranded people to safety. Hundreds of people died in the aftermath of Katrina because others, including police, vigilantes, high government officials and the media, decided that the people of New Orleans were too dangerous to allow them to evacuate the septic, drowned city, or to rescue them, even from hospitals. Some who attempted to flee were turned back at gunpoint or shot down. Rumors proliferated about mass rapes, mass murders, and mayhem that turned out later to be untrue, though the national media and New Orleans’s police chief believed and perpetrated those rumors during the crucial days when people were dying on rooftops, elevated highways and in crowded shelters and hospitals in the unbearable heat without adequate water, without food, without medicine and medical attention. Those rumors led soldiers and others dispatched as rescuers to regard victims as enemies. Others were murdered as a result, but not by the people the media scrutinized. Beliefs matter—though more people act beautifully despite their beliefs than the reverse.
						<br><br>
						Katrina was an extreme version of what goes on in many disasters, where how you behave depends on whether you think your neighbors or fellow citizens are a greater threat than the havoc wrought by a disaster or a greater good than the property in houses and stores around you. (Citizen, here, means members of a city or community, not people in possession of legal citizenship in a nation.) What you believe shapes how you act. How you act results in life or death, for yourself or others, like everyday life, only more so. Katrina was, like most disasters, also full of altruism: of young men who took it upon themselves to supply water, food, diapers, and protection to the strangers stranded with them, to people who sheltered neighbors, to the uncounted hundreds or thousands who set out in boats—armed, often, but also armed with compassion—to find those who were stranded in the stagnant waters and bring them to safety, to the two hundred thousand or more who volunteered to house complete strangers, mostly in their own homes, via the Internet site hurricanehousing.org in the weeks after, more persuaded by the pictures of suffering than the rumors of monstrosity, to the uncounted tens of thousands of volunteers who came to the Gulf Coast to rebuild and restore.
						<br><br>
						In the wake of an earthquake, a bombing or a major storm, most people are altruistic, urgently engaged in caring for themselves and those around them, strangers and neighbors as well as friends and loved ones. The image of the selfish, panicky or regressively savage human being in times of disaster has little truth to it. Decades of meticulous sociological research on behavior in disasters, from the bombings of World War II to floods, tornadoes, earthquakes and storms across the continent and around the world, have demonstrated this. But belief lags behind, and often the worst behavior in the wake of a calamity is on the part of those who believe that others will behave savagely and that they themselves are taking defensive measures against barbarism. From 1906 San Francisco to 2005 New Orleans, innocents have been killed by people who believed that their victims were the criminals and they themselves were the protectors of the shaken order. Belief matters.
						<br><br>
						“Today Cain is still killing his brother” proclaims a faded church mural on wood siding in the Lower Ninth Ward of New Orleans that was so devastated by the failure of the government levees. In quick succession, the Book of Genesis gives us the creation of the universe, the illicit acquisition of knowledge, the expulsion from Paradise, and the slaying of Abel by Cain, a second fall from grace into jealousy, competition, alienation, and violence. When God asks where his brother is, Cain asks back, “Am I my brother’s keeper?” He is refusing to say what God already knows: that the spilled blood of Abel cries out from the ground that has absorbed it. He is also raising one of the perennial social questions: are we beholden to each other, must we take care of each other, or is it every man for himself? Most traditional societies have deeply entrenched commitments and connections between people, families, and groups. The very concept of society rests on the idea of networks of affinity and affection, and the freestanding individual exists largely as an outcast or exile.
						<br><br>
						Mobile and individualistic modern societies shed some of these old bonds and vacillate about taking on others, particularly those expressed through economic arrangements—particularly provisions for the aged and vulnerable, the mitigation of poverty and desperation—the keeping of one’s brothers and sisters. The argument against such keeping is often framed as an argument about human nature: we are essentially selfish, and because you will not care for me, I cannot care for you. I will not feed you because I must hoard against starvation, since I too cannot count on others. Better yet, I will take your wealth and add it to mine—if I believe that my wellbeing is independent of yours or pitted against yours—and justify my conduct as natural law. If I am not my brother’s keeper, then we have been expelled from paradise, a paradise of unbroken solidarities.
						<br><br>
						Thus does everyday life become a social disaster. Sometimes disaster intensifies this; sometimes it provides a remarkable reprieve from it, a view into another world for our other selves. When all the ordinary divides and patterns are shattered, people step up—not all, but the great preponderance—to become their brothers’ keepers. And that purposefulness and connectedness bring joy even amidst death, chaos, fear and loss. Were we to know and believe this, our sense of what is possible at any time might change. We speak of self-fulfilling prophesies, but any belief that is acted on makes the world in its image. Beliefs matter. And so do the facts behind them. When it comes to human behavior in disaster, the gap between common beliefs and actualities limits the possibilities. Changing beliefs could fundamentally change much more. Horrible in itself, disaster is sometimes a door back into paradise, the realm in which we are who we hope to be, do the work we desire and are each our sisters’ and  brothers’ keepers.
						<br><br>
						I landed in Halifax, Nova Scotia, shortly after a big hurricane tore up the city in October of 2003.  The man in charge of taking me around told me about the hurricane—not the winds at more than a hundred miles an hour that tore up trees, roofs, telephone poles, not the seas that rose nearly ten feet, but the neighbors. He spoke of the few days when everything was disrupted and lit up with happiness as he did so. In his neighborhood all the people had come out of their houses to speak with each other, aid each other, to improvise a community kitchen, make sure the elders were okay, and spend time together, no longer strangers. “Everybody woke up the next morning and everything was different,” he mused. “There was no electricity, all the stores were closed, no one had access to media. The consequence was that everyone poured out into the street to bear witness. Not quite a street party, but everyone out at once—it was a sense of happiness to see everybody even though we didn’t know each other.” His joy struck me powerfully.
						<br><br>
						A friend told me of being trapped in a terrible fog, one of the dense tule fogs that overtakes California’s Central Valley periodically. On this occasion the fog mixed with dust from the cotton fields created a shroud so perilous that the highway patrol stopped all traffic on the highway. For two days she was stranded with many others in a small diner. She and her husband slept upright, shoulder to shoulder with strangers, in the banquettes of the diner’s booths, food and water began to run short, and they began to have a marvelous time. The people gathered there had little in common, but they all opened up, began to tell each other the stories of their lives, and by the time the road was safe, they were reluctant to go, but they went onward, home to New Mexico for the holidays. There everyone looked at them perplexedly as they told the story of their stranding with such ebullience. That time in the diner was the first time ever her partner, a Native American, had felt a sense of belonging in society at large. Such redemption amid disruption is common.
						<br><br>
						This past week, we’ve been given hell; survival for some of us is going to depend on how well we build the paradises of active love, sanctuary, refuge, and generosity. Love and empathy are acts of imagination, imagination is an act of courage, of risk; heroic love is what is going to get us through as much as we can. Here’s a little bit about what that has looked like before.
						<br><br>
						Who are you? Who are we? In times of crisis, these are life and death questions. Thousands of people survived Hurricane Katrina because grandsons or aunts or neighbors or complete strangers reached out to those in need all through the Gulf Coast and because an armada of boat owners from the surrounding communities and as far away as Texas went into New Orleans to pull stranded people to safety. Hundreds of people died in the aftermath of Katrina because others, including police, vigilantes, high government officials and the media, decided that the people of New Orleans were too dangerous to allow them to evacuate the septic, drowned city, or to rescue them, even from hospitals. Some who attempted to flee were turned back at gunpoint or shot down. Rumors proliferated about mass rapes, mass murders, and mayhem that turned out later to be untrue, though the national media and New Orleans’s police chief believed and perpetrated those rumors during the crucial days when people were dying on rooftops, elevated highways and in crowded shelters and hospitals in the unbearable heat without adequate water, without food, without medicine and medical attention. Those rumors led soldiers and others dispatched as rescuers to regard victims as enemies. Others were murdered as a result, but not by the people the media scrutinized. Beliefs matter—though more people act beautifully despite their beliefs than the reverse.
						<br><br>
						Katrina was an extreme version of what goes on in many disasters, where how you behave depends on whether you think your neighbors or fellow citizens are a greater threat than the havoc wrought by a disaster or a greater good than the property in houses and stores around you. (Citizen, here, means members of a city or community, not people in possession of legal citizenship in a nation.) What you believe shapes how you act. How you act results in life or death, for yourself or others, like everyday life, only more so. Katrina was, like most disasters, also full of altruism: of young men who took it upon themselves to supply water, food, diapers, and protection to the strangers stranded with them, to people who sheltered neighbors, to the uncounted hundreds or thousands who set out in boats—armed, often, but also armed with compassion—to find those who were stranded in the stagnant waters and bring them to safety, to the two hundred thousand or more who volunteered to house complete strangers, mostly in their own homes, via the Internet site hurricanehousing.org in the weeks after, more persuaded by the pictures of suffering than the rumors of monstrosity, to the uncounted tens of thousands of volunteers who came to the Gulf Coast to rebuild and restore.
						<br><br>
						In the wake of an earthquake, a bombing or a major storm, most people are altruistic, urgently engaged in caring for themselves and those around them, strangers and neighbors as well as friends and loved ones. The image of the selfish, panicky or regressively savage human being in times of disaster has little truth to it. Decades of meticulous sociological research on behavior in disasters, from the bombings of World War II to floods, tornadoes, earthquakes and storms across the continent and around the world, have demonstrated this. But belief lags behind, and often the worst behavior in the wake of a calamity is on the part of those who believe that others will behave savagely and that they themselves are taking defensive measures against barbarism. From 1906 San Francisco to 2005 New Orleans, innocents have been killed by people who believed that their victims were the criminals and they themselves were the protectors of the shaken order. Belief matters.
						<br><br>
						“Today Cain is still killing his brother” proclaims a faded church mural on wood siding in the Lower Ninth Ward of New Orleans that was so devastated by the failure of the government levees. In quick succession, the Book of Genesis gives us the creation of the universe, the illicit acquisition of knowledge, the expulsion from Paradise, and the slaying of Abel by Cain, a second fall from grace into jealousy, competition, alienation, and violence. When God asks where his brother is, Cain asks back, “Am I my brother’s keeper?” He is refusing to say what God already knows: that the spilled blood of Abel cries out from the ground that has absorbed it. He is also raising one of the perennial social questions: are we beholden to each other, must we take care of each other, or is it every man for himself? Most traditional societies have deeply entrenched commitments and connections between people, families, and groups. The very concept of society rests on the idea of networks of affinity and affection, and the freestanding individual exists largely as an outcast or exile.
						<br><br>
						Mobile and individualistic modern societies shed some of these old bonds and vacillate about taking on others, particularly those expressed through economic arrangements—particularly provisions for the aged and vulnerable, the mitigation of poverty and desperation—the keeping of one’s brothers and sisters. The argument against such keeping is often framed as an argument about human nature: we are essentially selfish, and because you will not care for me, I cannot care for you. I will not feed you because I must hoard against starvation, since I too cannot count on others. Better yet, I will take your wealth and add it to mine—if I believe that my wellbeing is independent of yours or pitted against yours—and justify my conduct as natural law. If I am not my brother’s keeper, then we have been expelled from paradise, a paradise of unbroken solidarities.
						<br><br>
						Thus does everyday life become a social disaster. Sometimes disaster intensifies this; sometimes it provides a remarkable reprieve from it, a view into another world for our other selves. When all the ordinary divides and patterns are shattered, people step up—not all, but the great preponderance—to become their brothers’ keepers. And that purposefulness and connectedness bring joy even amidst death, chaos, fear and loss. Were we to know and believe this, our sense of what is possible at any time might change. We speak of self-fulfilling prophesies, but any belief that is acted on makes the world in its image. Beliefs matter. And so do the facts behind them. When it comes to human behavior in disaster, the gap between common beliefs and actualities limits the possibilities. Changing beliefs could fundamentally change much more. Horrible in itself, disaster is sometimes a door back into paradise, the realm in which we are who we hope to be, do the work we desire and are each our sisters’ and  brothers’ keepers.
						<br><br>
						I landed in Halifax, Nova Scotia, shortly after a big hurricane tore up the city in October of 2003.  The man in charge of taking me around told me about the hurricane—not the winds at more than a hundred miles an hour that tore up trees, roofs, telephone poles, not the seas that rose nearly ten feet, but the neighbors. He spoke of the few days when everything was disrupted and lit up with happiness as he did so. In his neighborhood all the people had come out of their houses to speak with each other, aid each other, to improvise a community kitchen, make sure the elders were okay, and spend time together, no longer strangers. “Everybody woke up the next morning and everything was different,” he mused. “There was no electricity, all the stores were closed, no one had access to media. The consequence was that everyone poured out into the street to bear witness. Not quite a street party, but everyone out at once—it was a sense of happiness to see everybody even though we didn’t know each other.” His joy struck me powerfully.
						<br><br>
						A friend told me of being trapped in a terrible fog, one of the dense tule fogs that overtakes California’s Central Valley periodically. On this occasion the fog mixed with dust from the cotton fields created a shroud so perilous that the highway patrol stopped all traffic on the highway. For two days she was stranded with many others in a small diner. She and her husband slept upright, shoulder to shoulder with strangers, in the banquettes of the diner’s booths, food and water began to run short, and they began to have a marvelous time. The people gathered there had little in common, but they all opened up, began to tell each other the stories of their lives, and by the time the road was safe, they were reluctant to go, but they went onward, home to New Mexico for the holidays. There everyone looked at them perplexedly as they told the story of their stranding with such ebullience. That time in the diner was the first time ever her partner, a Native American, had felt a sense of belonging in society at large. Such redemption amid disruption is common.
					</h5>
				</div>
			</div>
		</main>
		<script src="../vendor.js"></script>
		<script src="js/script.js"></script>
	</body>
</html>
